apiVersion: v1
data:
  alertmanager.yml: |
    global:
      wechat_api_url: "https://qyapi.weixin.qq.com/cgi-bin/"
    templates: 
      - '/etc/alerttemplate/*.tmpl'
    route:
      receiver: "wechat"
      group_by: ['alertname', 'k8scluster', 'node', 'container', 'exported_job', 'daemonset']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
    receivers:
    - name: 'wechat'
      wechat_configs:
      - corp_id: 'ww63adb0909f572435'
        to_party: '1658018734'
        agent_id: '1000057'
        api_secret: 'z2x1-IDCSDJAxwkx32t2P_Ti-9UloQWtVDMX4jqaiy4'
    inhibit_rules:
    - source_match:
      namespace: "spider"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-rules
  namespace: default
