apiVersion: v1
data:
  wechat.tmpl: |
    {{- define "__text_alert_list" -}}
    {{- range .Alerts.Firing -}}
    Alerts Firing:
    告警级别: {{ .Labels.severity }}
    告警类型: {{ .Labels.alertname }}
    故障时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    故障详情: {{ .Annotations.summary }}
    ======参考信息======
    cluster: {{ .Labels.k8scluster }}
    namespace: {{ .Labels.namespace }}
    pod: {{ or .Labels.pod  .Labels.pod_name }}
    container: {{ .Annotations.container }}
    {{ end }}
    {{- range .Alerts.Resolved -}}
    Alerts Resolved:
    告警级别: {{ .Labels.severity }}
    告警类型: {{ .Labels.alertname }}
    故障详情: {{ .Annotations.summary }}
    触发时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    恢复时间: {{ (.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    {{ end }}
    {{- end }}

    {{- define "wechat.default.message" -}}
    {{- if gt (len .Alerts.Firing) 0 -}}
    {{ template "__text_alert_list" . }}
    {{- end }}
    {{- if gt (len .Alerts.Resolved) 0 -}}
    {{ template "__text_alert_list" . }}
    {{- end }}
    {{- end }}
kind: ConfigMap
metadata:
  name: alertmanager-tmpl
  namespace: default
