apiVersion: v1
data:
  wechat.tmpl: |
    {{ define "wechat.default.message" }}
    {{- if gt (len .Alerts.Firing) 0 -}}
    {{- range $index, $alert := .Alerts -}}
    {{- if eq $index 0 -}}
    告警类型: {{ $alert.Labels.alertname }}
    告警级别: {{ $alert.Labels.severity }}
    故障时间: {{ $alert.StartsAt.Format "2006-01-02 15:04:05" }}
    故障详情: {{ $alert.Annotations.summary }}
    ===参考信息===
    cluster: {{ $alert.Labels.k8scluster }}
    namespace: {{ $alert.Labels.namespace }}
    pod: {{ or $alert.Labels.pod  $alert.Labels.pod_name }}
    container: {{ $alert.Annotations.container }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
kind: ConfigMap
metadata:
  name: alertmanager-tmpl
  namespace: default
