apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: default
data:
  rule.rules: |
    groups:
    - name: kubernetes
      rules:
      - alert: PodDown
        expr: kube_pod_status_phase{phase="Unknown"} == 1 or kube_pod_status_phase{phase="Failed"} == 1
        for: 1m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Down."
          k8scluster: "{{ $labels.k8scluster}}"
          namespace: "{{ $labels.namespace }}" 
          pod: "{{ $labels.pod }}"
          container: "{{ $labels.container }}"

      - alert: PodPending
        expr: kube_pod_status_phase{phase="Pending"} == 1
        for: 5m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }} pod status is Pending 在5分钟内."
          k8scluster: "{{ $labels.k8scluster}}"
          namespace: "{{ $labels.namespace }}" 
          pod: "{{ $labels.pod }}"
          container: "{{ $labels.container }}"

      - alert: PodRestart
        expr: changes(kube_pod_container_status_restarts_total{pod !~ "analyzer.*"}[10m]) > 0
        for: 3m
        labels:
          severity: warn
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod }}  在一分钟内重启{{ $value }}次."
          k8scluster: "{{ $labels.k8scluster}}"
          namespace: "{{ $labels.namespace }}"
          pod: "{{ $labels.pod }}"
          container: "{{ $labels.container }}"
    
      - alert: NodeUnschedulable
        expr: kube_node_spec_unschedulable == 1
        for: 5m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Node: {{ $labels.node }} Unschedulable 在五分钟内未恢复"
          k8scluster: "{{ $labels.k8scluster}}" 
          node: "{{ $labels.node }}"
    
      - alert: NodeStatusError
        expr: kube_node_status_condition{condition="Ready", status!="true"} == 1
        for: 2m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Node: {{ $labels.node }} Status Error"
          k8scluster: "{{ $labels.k8scluster}}" 
          node: "{{ $labels.node }}"
    
      - alert: DaemonsetUnavailable
        expr: kube_daemonset_status_number_unavailable > 0
        for: 5m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Daemonset: {{ $labels.daemonset }} Status Unavailable"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}"  
          daemonset: "{{ $labels.daemonset }}"
    
      - alert: JobFailed
        expr: kube_job_status_failed == 1
        for: 5m
        labels:
          severity: error
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Job: {{ $labels.job_name}} Status Failed"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}" 

      - alert: PodCPUUsage
        expr: (sum(rate(container_cpu_usage_seconds_total{image!="",namespace != "kube-system"}[3m])) by (pod_name, namespace,k8scluster)) / (sum(container_spec_cpu_quota{image!="",namespace != "kube-system"}/100000) by (pod_name, namespace,k8scluster)) * 100 > 90
        for: 3m
        labels:
          severity: warn
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod_name }}  CPU使用率大于90%. (当前值:{{ $value }}%)"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}" 

      - alert: PodMemUsage
        expr: sum(container_memory_rss{image!="",namespace != "kube-system"}) by(pod_name, namespace,k8scluster) / sum(container_spec_memory_limit_bytes{image!="",namespace != "kube-system"}) by(pod_name, namespace,k8scluster) * 100 != +inf > 90
        for: 3m
        labels:
          severity: warn
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod_name }}  内存使用率大于90%. (当前值:{{ $value }}%)"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}" 

      - alert: PodTX
        expr: sum (rate (container_network_transmit_bytes_total{image!="",namespace!="kube-system",pod_name!~"^node-exporter-.*"}[5m]) /1000) by (pod_name,namespace,k8scluster) > 20000
        for: 3m
        labels:
          severity: warn
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod_name }}  传输的流量超过20MB/s. (当前值:{{ $value }}%)"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}"

      - alert: PodRX
        expr: sum (rate (container_network_transmit_bytes_total{image!="",namespace!="kube-system",pod_name!~"^node-exporter-.*"}[5m]) /1000) by (pod_name,namespace,k8scluster) > 20000
        for: 3m
        labels:
          severity: warn
          service: prometheus_bot
          receiver_group: "{{ $labels.k8scluster}}_{{ $labels.namespace }}"
        annotations:
          summary: "Namespaces: {{ $labels.namespace }} | PodName: {{ $labels.pod_name }}  接收到的流量超过20MB/s. (当前值:{{ $value }}%)"
          k8scluster: "{{ $labels.k8scluster}}" 
          namespace: "{{ $labels.namespace }}"
